import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link.js';
import { Button } from '../components/ui/button';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="flex justify-between p-8 mb-8 bg-gray-100">
            <h1 className="text-2xl font-bold">
              <Link href="/">LOGO</Link>
            </h1>
            <Button asChild>
              <Link href="/login">Login</Link>
            </Button>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
